### PR TITLE
Full time detail option for GSA

### LINKED ISSUE #988: As a GSA employee, need the ability to post full-time detail opportunities
Include information unique to the detail task type such as:
-Link to application process and process information
-Restrictions on who is eligible to apply (i.e.GSA only)

### PR DESCRIPTION
**Pull request by jeremiak**
This pull request should be the first iteration of the full time detail feature. Changes to the application are as follows:

0. There is a script to add a "Full time detail" tag that is restricted to GSA affiliated users
0. A task creator who is also a GSA affiliated user can create tasks with this new tag
0. GSA affiliated users looking for tasks through the regular search interface will see these opportunities, but users that don't have GSA as their agency will not be able to see these tasks.

@GailSwanson ready for your review

To close #988 #989 #990

### CODE REVIEW

**Comment by ultrasaurus** [comment]
@jeremiak haven't looked at the code, just want to make sure that if someone at GSA sends someone else at GSA a direct link to the task, it doesn't require login... is that how it works?

**Comment by jeremiak** [comment]
@ultrasaurus Yup! Anybody can send anybody else a link for a task (https://openopps.digitalgov.gov/tasks/387 for example) and they can view it without authentication.

**Comment by GailSwanson** [comment]
We should make sure that doesn't open any back door entry points to unauthenticated users viewing PII, such as the task creator's profile.

**Comment by ultrasaurus** [comment]
@GailSwanson I don't expect that to happen since this is old behavior, but would be good to make sure we have automated tasks for that.

FYI: for government use of Midas, there is no PII in the system.  All of our information as federal employees is a matter of public record -- we require the use of work email address and locations are work locations.  However, we don't want to open up the system to spammers and want to support private sector / non-gov use cases, so your point is absolutely valid, just not technically a PII concern.

**Comment by dhcole** [comment]
This pr does not change profile visibility. And issues with profile visibility should be addresses separately.

**Comment by dhcole** [comment]
What I mean by that is that all this PR does is hide tasks in search. All the rest of how tasks or profiles are visible remains the same. There should not be any issues there, but if there are, researching and addressing them are out of scope this this PR

**Comment by jeremiak** [comment]
I should've added this to the original PR but this does require a script be run to add the new tag for Full Time details at GSA. From the project root, you should run:
`node tools/postgres/addGSAFullTimeDetail.js` and then start the server normally

**Comment by dhcole** [comment]
@jeremiak I updated with two small changes. The biggest one is that if you try to create a task after logging in, you got an error, because the profile returned from the authentication endpoint didn't populate tags. I fixed this by adding in an additional request to get the user's full profile.

I'll merge once tests pass.

**Comment by GailSwanson** [comment]
It took a chunk of time for @jeremiak and I to get issues ironed out so that I could view the PR. All good now.

**Pull request merged**
