### PR TITLE
Better tags for task time lengths

### PR DESCRIPTION
**Pull request by jeremiak**
This PR changes the copy on task creating/editing views to reflect a few new tags related to task length. Specifically this should address #290 as it changes the tags loaded by default (upon running `npm run init`) and also the copy for the task views.

An open question I still have is if we want to move the old tags over to the new names, and what we should do in the cases where there isn't a clear mapping. For instance, should we map "20%" time to "on going?"

### CODE REVIEW

**Comment by dhcole** [comment]
@jeremiak This is looking good. Per conversations in stand up, are you taking a look at a data update script to move old tags to the new ones in this PR?

**Comment by jeremiak** [comment]
@dhcole as soon as we finalize the copy changes per #290 this should be good for :eyes:. The end result is a data migration script that is idempotent and does a three distinct tasks:

0. Renames tags that have a direct mapping
0. Adds new tags that were not present before
0. Migrates associated users, projects, and tasks off of old tags and onto new ones. It then deletes the old tags from the database.

**Comment by jeremiak** [comment]
I believe this is ready for testing as I followed @GailSwanson's advice per #290

**Comment by dhcole** [comment]
Looks good. 

*Developer note*: run `node tools/postgres/migrateOldTags.js` to migrate to the new tags.

**Pull request merged**
