### PR TITLE
New profile view

### LINKED ISSUE #962: Profile Page: Look at overall design / usability
- https://github.com/18F/midas/issues/698
- https://github.com/18F/midas/issues/841

### PR DESCRIPTION
**Pull request by jeremiak**
The implementation of the new profile, which includes changes to both the display and editing views, per the designs in #962.

@GailSwanson this should be ready for your review.

As a note, badges have been removed from this implementation (though they appear in the designs), but will be re-tackled alongside issue #979.

Resolves #962

### CODE REVIEW

**Comment by dhcole** [comment]
@GailSwanson have you had a chance to review this? Also, check out the docker container for local testing: https://github.com/18F/midas/blob/devel/INSTALL.md#deploy-midas-as-a-docker-container-from-the-docker-hub-mac-windows-linux

**Comment by GailSwanson** [comment]
Yes. Looks fantastic. Only minor tweaking needed on edit view

Copy for info blocks is forthcoming
Remove LinkedIn option (per conversation)
Increase space above "Account Information" heading
Increase space above Save and cancel buttons.

**Comment by jeremiak** [comment]
Changes made per @GailSwanson's comment above. Ready for :eyes: and :ship: (:pray:)

**Comment by dhcole** [comment]
Nice work on this! :ship:

**Pull request merged**
