### PR TITLE
Task creation fixes and design tweaks

### LINKED ISSUE #956: Error when saving tasks in 0.7.0
Reported by @GailSwanson, when saving a task the server returns `POST http://localhost:1337/api/task 500 (Internal Server Error)` with the following in the log:

```
error: Sending 500 ("Server Error") response: 
 Error (E_UNKNOWN) :: Encountered an unexpected error
error: invalid input syntax for type timestamp with time zone: ""
    at Connection.parseE (/Users/davidcole/dev/midas/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:534:11)
    at Connection.parseMessage (/Users/davidcole/dev/midas/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:361:17)
    at Socket.<anonymous> (/Users/davidcole/dev/midas/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
    at TCP.onread (net.js:529:21)

Details:  error: invalid input syntax for type timestamp with time zone: ""
```

### LINKED ISSUE #957: Opportunity Creation Interface Fixes
- [x] Create an Opportunity should be in title case (capitalize “Opportunity”)
- [x] “If you’re new…” copy should be set apart by a padded colored border(not red).
- [x] Link “10 Tips for Creating the Perfect Open Opportunity Task” to http://www.digitalgov.gov/resources/open-opportunities-task-creator-toolkit/10-tips-for-creating-the-perfect-open-opportunity-task/
- [ ] Adjust line spacing to match design 
- [x] Change “All fields required.” to “Optional fields are indicated.” 
- [x] Additional line spacing above step 1 heading.
- [x] Use title case for step headings. (i.e. Create a Headline, Describe the Opportunity)
- [x] Left justify field labels with other text.
- [x] Reduce line spacing within instructional text (above field)
- [x] Italicize instructional text with parentheses (reference wireframe)
- [x] Remove hint text inside headline and description 
- [x] Description instructional text should read: “Write a description that explains the opportunity. Add details so that people can imagine what this will be like when completed. There is no limit on length, but we recommend 200 words or less.)”
- [x] Add line spacing above Tags heading
- [x] Add period at end of Tags instruction text.
- [x] Update in-field hint text to read “Start typing to select a tag.”
- [x] Add rest of One time label: “One time — A one time task with a defined timeline”
- [x] Add rest of Ongoing label: “Ongoing  — Requires a portion of participant’s time until a goal is reached"
- [x] Update “Specific location(s):” to “At specific locations:”
- [x] Add line space above buttons
- [x] Add spacing between buttons so to minimize mis-clicks. Right align buttons on page
- [x] Change “Create” button label to read “Submit for Review”
- [x] Update background on text rectangles to dark grey (#797979) and text as white
- [x] Estimated completion date should be optional
- [x] When Ongoing is selected, display the Example text rectangle at right
- [x] Values for “How often is this time needed?” selector should be: Weekly, Biweekly, Monthly
screen shot 2015-08-14 at 3 12 41 pm

### PR DESCRIPTION
**Pull request by jeremiak**
Our new task creation feature deviated from the (now) agreed upon protocol for features that span design and development. In the future, we will ping @GailSwanson/design in the original PR so that we can sort out bugs and design changes in nice, discreet bunches.

That being said, now that we've merged in #932 we have some technical and design bugs to work out (#956, #957) which this PR will address when it is labelled as *Ready for Review*.

There are a few overlapping changes between this PR and #954 so I'll probably accept the #954 changes into `devel` and make sure this branch has no merge conflicts.

Resolves #957 
Resolves #956

### CODE REVIEW

**Comment by dhcole** [comment]
@jeremiak cool, is this read for @GailSwanson and me to review?

**Comment by jeremiak** [comment]
@dhcole almost, just one last tag migration script to run so that:
> Values for “How often is this time needed?” selector should be: Weekly, Biweekly, Monthly 

Will ping both of you and label appropriately shortly

**Comment by jeremiak** [comment]
@dhcole and @GailSwanson - this should be ready to review. Feel free to make lists of items that I need to complete before merging on this issue for easier bookkeeping.

**Comment by GailSwanson** [comment]
Visual Feedback

[ ] Contrast between blue information block background and blue hyperlink is too low contrast for 508. If we remove the blue gradient background and just have a 1px blue border that should solve it.
[ ] Step 3 - Ongoing radio button label should read "Ongoing  — Requires a portion of participant’s time until a goal is reached"
[ ] "How often is this time needed?" selection options are not updated (perhaps an issue on my end)
[ ] 24p is adequate spacing between action buttons (aligned right)
[ ] Link color within the grey info boxes is too low contrast for 508. #00FFFF is a good one.
[ ] Field level error messages- make red and place above relevant field

**Comment by jeremiak** [comment]
Thanks @GailSwanson! I'll get right on these. As far as the `task-length` tags ("How often is this time needed" options), you'll need to run a migration script so that you can update the database. You should be able to run `node /tools/postgres/migrateOldTags.js` from the root level of the midas project.

**Comment by jeremiak** [comment]
@dhcole this is ready for a technical review, and I do believe all the visual feedback has been implemented cc @GailSwanson 

There are changes to `/tools/postgres/migrateOldTags.js` so make sure to run that before inspecting the changes.

**Comment by dhcole** [comment]
:+1: Looks great. Merging so we can review on the staging server.

**Comment by GailSwanson** [comment]
screen shot 2015-08-17 at 5 48 33 pm

Looks like the Ongoing radio label hasn't updated and the drop down options haven't updated.

**Pull request merged**
