### PR TITLE
MyUSA Configuration

### PR DESCRIPTION
**Pull request by dhcole**
Addresses tasks related to MyUSA integration.

First round includes:

- If user has an existing account (based on email address) merge it with new MyUSA credentials
- Don't create multiple MyUSA accounts on subsequent log-ins.

### CODE REVIEW

**Comment by dhcole** [comment]
@ultrasaurus this + a change to the cookbook should have myusa auth working again. Can you let me know what you think of these workflow changes?

## Currently

Signing in with MyUSA created a new account every time. Sign in with MyUSA 5 times, you'd have 5 accounts. 

Signing in with MyUSA after you have already set up a local (username and password) account would create a new account.

## With this PR

Signing in with MyUSA only creates a new account once if no other account exists in the system.

Signing in with MyUSA will log you into an existing local account with the same username (email), bypassing the password authentication and linking the MyUSA credentials to your existing account.

---

If you're good with this workflow, than this should be good to merge.

**Comment by ultrasaurus** [comment]
I like this workflow.

**Comment by dhcole** [comment]
Ok, I made those updates.

**Comment by ultrasaurus** [comment]
wonderful -- looking forward to trying this out!  Will wait to merge till ok by Travis, but should be fine

**Comment by dhcole** [comment]
Great! https://github.com/18F/midas-cookbook/pull/27 also needs to be merged before deploying to the dev server.

**Pull request merged**
