### PR TITLE
Show alert message when user tries to add an oauth account that's linked to another Midas account

### PR DESCRIPTION
**Pull request by dhcole**
This addresses #708 by showing the user an error to tell them their oauth account is already linked to another account. 

@ultrasaurus How's this work for you?

screen shot 2015-04-22 at 1 03 12 pm

### CODE REVIEW

**Comment by ultrasaurus** [comment]
looks good to me

**Comment by ultrasaurus** [comment]
wait.... "this profile" actually is confusing

**Comment by ultrasaurus** [comment]
How about this:
"We're sorry, you can't connect that LinkedIn account since it is already connected to a different profile."

?

**Comment by dhcole** [comment]
I was trying to avoid the extra work of figuring out what provider is throwing the error :) This could happen with LinkedIn or MyUSA, or any other oauth provider we may add in the future. I'll look into how we can set this value dynamically...

**Comment by ultrasaurus** [comment]
alternate: "We're sorry, you can't connect an account that is already connected to a different profile."

**Comment by dhcole** [comment]
Found it: `sails.config.auth.config.config[userAuth.provider].name`

screen shot 2015-04-22 at 2 34 33 pm
screen shot 2015-04-22 at 2 34 19 pm

**Comment by ultrasaurus** [comment]
sweet :+1:

**Pull request merged**
