### PR TITLE
Actually reset user's passwordAttempts

### PR DESCRIPTION
**Pull request by dhcole**
After validating a reset token, we need to reset the count of password attempts so the user may log in.

Fixes: #509

### CODE REVIEW

**Comment by dhcole** [comment]
Depends on https://github.com/18F/sails-postgresql/pull/2

**Comment by dhcole** [comment]
That error is just returned from the JSON response. The UI always shows this message for any error:

> An error occurred resetting your password. Please reload this page and try again.

screen shot 2015-01-28 at 2 01 32 pm

**Comment by ultrasaurus** [comment]
Ok, I suppose that's fine then.  If reloading consistently fails, they will let us know.  I do wonder if we should be logging errors like this...

**Comment by ultrasaurus** [comment]
opened separate issue for logging, will merge this one

**Pull request merged**
