### PR TITLE
Allow admin to delete comments

### PR DESCRIPTION
**Pull request by brandtheisey**
This allows admins to delete non-topic comments.

How to handle topics in general and topics with replies specifically will be addressed at a later date.

This is a CrowdWork requested feature.

### CODE REVIEW

**Comment by brandtheisey** [comment]
Removed topic restriction as we are moving to flat - comments in #693

**Comment by brandtheisey** [comment]
If you deleted the only comment, the text encouraging you to start a discussion didn't appear, this fixes that.

**Comment by ultrasaurus** [comment]
need to fix admin console that displays notifications (recent activity feed) -- can just say "comment deleted"

**Comment by dhcole** [comment]
@brandtheisey take a look here: https://github.com/18F/midas/blob/devel/api/controllers/AdminController.js#L313

This throws an error when a comment has been deleted. I think we just need to check to see `if(comment)` and then return something generic like (deleted comment).

**Comment by ultrasaurus** [comment]
I'm fine with just omitting the line with the deleted comment, with no annotation that the comment is deleted

**Comment by dhcole** [comment]
Hey @brandtheisey any idea why there are a bunch of extra commits in this PR?

**Comment by brandtheisey** [comment]
I can close this and resubmit a new PR, I'm not sure what happened.

**Comment by dhcole** [comment]
@brandtheisey looking good. Found two things:

1. the "x" is a span and doesn't have the pointer cursor. Would this work as an `a` instead? Also, can you give it a width to make it a circle instead of oval?
2. deleting a comment shows default text even when there are other comments:

screen shot 2015-04-09 at 12 18 17 pm
screen shot 2015-04-09 at 12 18 23 pm

**Comment by dhcole** [comment]
Just to recap from our call: @brandtheisey is working on the following:

1. Push updated X design
2. Stop default content from appearing when comments are present
3. Add note about a manual data migration for pre-existing threaded comments

**Comment by brandtheisey** [comment]
@dhcole this has been tested to correctly handle pre-existing threaded comments and otherwise behaves as requested. There doesn't appear to be a need for a manual step.

**Comment by brandtheisey** [comment]
Also closes #706

**Comment by dhcole** [comment]
Looks great! Nice work @brandtheisey

**Pull request merged**
