### PR TITLE
D3 world map with users

### PR DESCRIPTION
**Pull request by sefk**
Partial fix to issue #672. Submitted here in case someone wants to take a look (pull branch, play with it). But probably needs some cleanup before asking for a thorough code review.

Text from commit below.

------------------
Add /map view that displays a world map with dots for all the users that have specified their own location. Currently colors and values are all hard-coded.

This is built off of mbostock's exceptional D3 library and borrows heavily from his examples. The world topo map is his 50m data file.

Add /api/user/all endpoint to dump out information for all users. Same access permissions as rest of the user endpoints.

This is a very rough initial version. 

- Efficiency of "all" endpoint needs to be improved
- Plot performance of lots of users is probably poor
- Plot performance of map itself on lower-end machines is probably not good enough, consider lower resolution maps
- Should add zoom, translate, etc.
- Needs spinner

Data flow through the map view is rough and should be refactored to take events into account.

### CODE REVIEW

**Comment by ultrasaurus** [comment]
Would be worth looking into a smaller map data file -- I would guess the 50m supports a more detailed zoom than we need.

Thanks for posting this work-in-progress.  I will try to play with it later today!

**Comment by dhcole** [comment]
> Would be worth looking into a smaller map data file -- I would guess the 50m supports a more detailed zoom than we need.

FWIW, I think this is a pretty standard geojson file for world maps. It should gzip down to around 120k, which isn't crazy for this kind of feature. I'd vote for getting this working well and then go back and optimize.

**Comment by dhcole** [comment]
Actually, I just found about  a 110m file. Try this and see if it isn't too coarse: https://gist.githubusercontent.com/mbostock/4090846/raw/4efd24ad87179c1eeafd57cfb0978c8f45730036/world-110m.json

**Comment by sefk** [comment]
It's interesting to compare the 50m and 110m maps. Screenshots of the two are attached, and I'm not sure which one I prefer.

The 110m, at first glance, is cleaner. Note the western coast of Canada and southern Alaska: instead of seeing a cluttered coastline, you just see the border. But then again, you are missing a ton of islands -- much of Indonesia, the south pacific, and the caribbean is missing!

world-50m.json - 727k
world-110m.json - 99k

50m
110m

**Comment by dhcole** [comment]
Since you're not supporting zooming, I'd go with 110m.

**Comment by sefk** [comment]
OK @dhcole that's what's in the code now. It's at a good stopping point. We can add a ton of future features later: zoom, pan, push position to navbar for linking, search on users, tooltips for user profiles, aggregate by city...

So: this is ready for code review. Thanks.

**Comment by sefk** [comment]
Closing now that this will be merged into #673 .

**Pull request closed without merging**
