### PR TITLE
Fix Bad escaping in email subject line

### PR DESCRIPTION
**Pull request by awhig**
Subject line of email was HTML escaped. It
no longer does this.

https://github.com/18F/midas/issues/903

### CODE REVIEW

**Comment by jeremiak** [comment]
I wonder if this build failure is the same thing @dhcole was seeing in #935. I'll try cutting a new branch and merging it in to see if it works on Travis. If it does I'll make that commit to this PR and delete the old branch.

**Comment by jeremiak** [comment]
Hey @awhig would you mind merging in the latest `18f/midas/devel`? It pins the `npm` version for Travis to use and results in a [passing build](https://travis-ci.org/18F/midas/builds/74331165). Thanks!

**Comment by awhig** [comment]
@jeremiak I merged the latest code in...

**Comment by jeremiak** [comment]
Awesome, LGTM @awhig - merging now

**Pull request merged**
