### PR TITLE
policy on reviewing pull requests

### PR DESCRIPTION
**Pull request by ultrasaurus**
I couldn't find this written up anywhere
so I added to Contribution Guide

### CODE REVIEW

**Comment by dhcole** [comment]
:+1: good call!

**Comment by sefk** [comment]
Nice clarification @ultrasaurus :+1:

**Comment by brandtheisey** [comment]
+1

**Comment by jeremiak** [comment]
Looks great, thanks @ultrasaurus - I see a few +1s so I'll take that as a few pairs of :eyes: have seen this and going to merge it.

**Pull request merged**
