### PR TITLE
Master

### PR DESCRIPTION
**Pull request by aifoS1**
Added a little more info regarding the running postgres and mentioned there may be an error when you run npm init.

### CODE REVIEW

**Comment by dhcole** [comment]
Hi @aifoS1 thanks for these updates. The postgres section is great.

`npm run init` should work the first time you run it on a DB. You should only see an error if you try to run it more than once on the same DB. I actually just posted about this in #739 this morning.

Think we should update that line to be more specific that you should only run `npm run init` once per database, otherwise you'll see an error?

**Comment by aifoS1** [comment]
Hi @dhcole, thanks glad I could help. Oh, interesting, I thought I ran it once, but maybe I did try to run it twice. Updating to be more specific regarding running it once can't hurt. Want me to update?

**Comment by dhcole** [comment]
Yea, that would be great. Then we can get this merged in. I think a follow up task would be to have the `init` script return a more useful error, but documenting here should help alleviate the confusion.

**Comment by aifoS1** [comment]
@dhcole great, updated!

**Comment by dhcole** [comment]
Great, thanks again @aifoS1!

**Pull request merged**
