### PR TITLE
Use standard postgres for vagrant

### PR DESCRIPTION
**Pull request by dlapiduz**

### CODE REVIEW

**Comment by ultrasaurus** [comment]
this fails when I run the branch locally
```
==> default: The following NEW packages will be installed:
==> default:   comerr-dev krb5-multidev libgssrpc4 libkadm5clnt-mit9 libkadm5srv-mit9
==> default:   libkdb5-7 libpq-dev libssl-dev libssl-doc zlib1g-dev
==> default: 0 upgraded, 10 newly installed, 0 to remove and 0 not upgraded.
==> default: Need to get 2,679 kB of archives.
==> default: After this operation, 10.8 MB of additional disk space will be used.
==> default: Get:1 http://archive.ubuntu.com/ubuntu/ trusty/main libgssrpc4 amd64 1.12+dfsg-2ubuntu4 [53.1 kB]
==> default: Get:2 http://archive.ubuntu.com/ubuntu/ trusty/main libkadm5clnt-mit9 amd64 1.12+dfsg-2ubuntu4 [36.1 kB]
==> default: Get:3 http://archive.ubuntu.com/ubuntu/ trusty/main libkdb5-7 amd64 1.12+dfsg-2ubuntu4 [36.2 kB]
==> default: Get:4 http://archive.ubuntu.com/ubuntu/ trusty/main libkadm5srv-mit9 amd64 1.12+dfsg-2ubuntu4 [50.2 kB]
==> default: Get:5 http://archive.ubuntu.com/ubuntu/ trusty/main comerr-dev amd64 2.1-1.42.9-3ubuntu1 [38.3 kB]
==> default: Get:6 http://archive.ubuntu.com/ubuntu/ trusty/main krb5-multidev amd64 1.12+dfsg-2ubuntu4 [111 kB]
==> default: Get:7 http://archive.ubuntu.com/ubuntu/ trusty/main zlib1g-dev amd64 1:1.2.8.dfsg-1ubuntu1 [183 kB]
==> default: Err http://archive.ubuntu.com/ubuntu/ trusty-updates/main libssl-dev amd64 1.0.1f-1ubuntu2.4
==> default:   404  Not Found [IP: 91.189.91.15 80]
==> default: Get:8 http://archive.ubuntu.com/ubuntu/ trusty/main libpq-dev amd64 9.3.4-1 [139 kB]
==> default: Err http://security.ubuntu.com/ubuntu/ trusty-security/main libssl-dev amd64 1.0.1f-1ubuntu2.4
==> default:   404  Not Found [IP: 91.189.91.13 80]
==> default: Err http://security.ubuntu.com/ubuntu/ trusty-security/main libssl-doc all 1.0.1f-1ubuntu2.4
==> default:   404  Not Found [IP: 91.189.91.13 80]
==> default: Fetched 647 kB in 12s (51.4 kB/s)
==> default: STDERR: E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl-dev_1.0.1f-1ubuntu2.4_amd64.deb  404  Not Found [IP: 91.189.91.13 80]
==> default: 
==> default: E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl-doc_1.0.1f-1ubuntu2.4_all.deb  404  Not Found [IP: 91.189.91.13 80]
==> default: 
==> default: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
==> default: ---- End output of apt-get -q -y install libpq-dev=9.3.4-1 ----
```

**Comment by dlapiduz** [comment]
I added the `apt-get update` to fix that issue but I am getting a new error:
```
==> default: STDOUT: lifting sails: env=development
==> default:   init:
    1) tags: 
==> default: 
==> default: 
==> default: Lowering sails
==> default: 
==> default:   0 passing (3s)
==> default:   1 failing
==> default: 
==> default:   1) init: tags:
==> default:      Error: done() invoked with non-Error: Error: Register unsuccessful. {
==> default:   "error": null,
==> default:   "message": "Error looking up user"
==> default: }
==> default:       at /var/www/midas/node_modules/mocha/lib/runnable.js:224:25
==> default:       at /var/www/midas/test/init/init/init.test.js:34:23
==> default:       at Request._callback (/var/www/midas/test/demo/data/utils.js:39:22)
==> default:       at Request.self.callback (/var/www/midas/node_modules/request/request.js:373:22)
==> default:       at Request.emit (events.js:98:17)
==> default:       at Request.<anonymous> (/var/www/midas/node_modules/request/request.js:1318:14)
==> default:       at Request.emit (events.js:117:20)
==> default:       at IncomingMessage.<anonymous> (/var/www/midas/node_modules/request/request.js:1266:12)
==> default:       at IncomingMessage.emit (events.js:117:20)
==> default:       at _stream_readable.js:944:16
==> default:       at process._tickDomainCallback (node.js:486:13)
==> default: STDERR: make: *** [init] Error 1
==> default: ---- End output of make init && touch /tmp/midas_init ----
==> default: Ran make init && touch /tmp/midas_init returned 2
```

**Comment by ultrasaurus** [comment]
@dlapiduz this is an issue with Sail .10 upgrade
@DavidEBest what do you think about switching the config 'alter' as part of ```make init```?

**Comment by ultrasaurus** [comment]
should work now with https://github.com/18F/midas/pull/490
I will test locally

**Comment by ultrasaurus** [comment]
Installation completes and I can see Midas running at http://localhost:8080 and sign up

**Pull request merged**
