### PR TITLE
Task assigned email notification

### PR DESCRIPTION
**Pull request by dhcole**
This is mostly done but we need to decide who gets this notification and whether more development is needed around the assignment workflow. 

Discussion in #579

### CODE REVIEW

**Comment by dhcole** [comment]
Updated to send to all participants in the `to` line. If that's acceptable, then this is ready to go. If we need to send separate emails to each participant, this will require more work.

**Comment by ultrasaurus** [comment]
I was going to suggest that approach.  However in the case of multiple recipients, not sure what value ```metadata.recipient.name``` will be.  Perhaps we should just omit Dear ______, in this case.

cc @LisaLNelson

**Comment by dhcole** [comment]
I updated it to "Dear Participants"

https://github.com/dhcole/midas/commit/fb71651c13e71aa0e3d13d978ec8d17031e7d8b4#diff-d3e1aaff94abc154fa93fbc76f2cc871R1

**Comment by ultrasaurus** [comment]
"Dear Participants" doesn't work for the singular case.  Just talked to @LisaLNelson and she agrees that just dropping "Dear ____" is good.  The email starts with "Great news..." which is a nice opener.

**Comment by dhcole** [comment]
Ok, removed it fe1e164e281aec96e4950ba06ca80aabfd29bf47

**Comment by ultrasaurus** [comment]
Thanks!

**Pull request merged**
