### PR TITLE
Add logging with winston

### PR DESCRIPTION
**Pull request by brandtheisey**
Basic logging with Winston. This should catch all current logging except the debug info thrown by i18n.

To use, you need to **npm install winston**

A couple of notes:
1) Winston uses different logging levels than sails (they are flipped), so the log_levels variable addresses that
2) Sails logging level (on line 68 of log.js) is the superset of available levels for other transports
3) The transport.Console is required to push info to the console and it will use the lesser of it's logging level and the sails logging level. Without it, you will see no logging information in the console.
4)Multiple transports of the same type can be created (if you wanted to write different levels to different files for instance) but they MUST have different **name** attributes or an error will be thrown.
5) The default log file needs to be given the appropriate full path when deployed.

Addresses #660

### CODE REVIEW

**Comment by dhcole** [comment]
@brandtheisey this is looking good. Two things:

1. Should we set the default log value to something less verbose?
2. Why have a file log by default? Can we keep only console logs by default and use a file case-by-case through the `local.js` file? If there's a good reason to do a file log, should it be in `.gitignore`?

**Comment by brandtheisey** [comment]
@dhcole I believe this addresses your concerns as the file logging is now working correctly in local.js and the default is just console log with timestamps. In the comments of the log.js file are instructions on how to add the fulling logging to local.js.

**Comment by dhcole** [comment]
@brandtheisey looks great! Any idea why so many old commits are in this PR now? Would be great to just have the commits related to this actual change so we can see a clean view of the history.

**Comment by dhcole** [comment]
Works well. Thanks @brandtheisey

**Pull request merged**
