### PR TITLE
new open source logo

### PR DESCRIPTION
**Pull request by ultrasaurus**
new logo for the open source project by @goodnightjj

### CODE REVIEW

**Comment by ultrasaurus** [comment]
resolves https://github.com/18F/midas/issues/1080

**Comment by rogeruiz** [comment]
This looks good. I'm really liking the blues. Good work @goodnightjj

**Comment by rogeruiz** [comment]
Taking a look at implications of merging this, should we wait to merge this until #907 is complete, @ultrasaurus?

**Comment by ultrasaurus** [comment]
I'm working on the README now.  I will integrate this PR

**Comment by rogeruiz** [comment]
Sounds good. You can assign the new PR to me and I can review it :+1:

**Pull request closed without merging**
