### PR TITLE
Change profile 'Topics' to 'Interests'

### LINKED ISSUE #839: Change "Topics" to "Interests" in Profile

### PR DESCRIPTION
**Pull request by jeremiak**
It is weird to say that "Topics" describe a user so this PR changes copy on the profile view to update "Topics" to "Interests". Per the conversation on #839, this is **only** for the profile view and not necessarily everywhere those tags show up in the application.

To close #839

### CODE REVIEW

**Comment by dhcole** [comment]
@jeremiak Is this ready to go? Do you mind merging in `devel` to get the tests passing?

**Comment by jeremiak** [comment]
@dhcole I'll merge with `devel` to make sure the tests pass. I'll also make sure to run the tests before I submit a pull request without the "Not ready" label, sorry about that.

**Comment by jeremiak** [comment]
@dhcole ready when you are

**Comment by dhcole** [comment]
:+1: looks great :ship:

**Pull request merged**
