### PR TITLE
Application & Theme CSS Refactor

### PR DESCRIPTION
**Pull request by rogeruiz**
This pull request introduces the following changes to the project:

- [x] Introduce Sass, Bourbon, Neat, (and Eyeglass) as development dependences to follow the [18F front-end conventions](https://pages.18f.gov/frontend/css-coding-styleguide/preprocessor/).
- [x] Modular architecture based on old application styles.
- [x] Replaced asset pipeline with passing smoke-tests
- [x] Check more pages to make sure there are no regressions
- [x] Set up modular architecture for the `theme.css` files
- [x] Create proper, *overridable*, defaults using the concepts outlined in #906

### CODE REVIEW

**Comment by rogeruiz** [comment]
Seems like the errors I'm seeing on Travis are related to the `select2` dependency. I'm going to try to blow away my local `node_modules` and see if I can reproduce this error locally.

```
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'select2/package.json'
Warning: Task "build" not found. Use --force to continue.
```

**Comment by rogeruiz** [comment]
Hey @jeremiak Could you take a look at this PR. You'll need to run `npm` install before being able to run `grunt` after checking out the branch. Currently, the theme's CSS has just been split apart. Should I do any further refactoring here to make it more overridable? I've already done this with the color variables on the top of the `theme/_base` file.

**Comment by jeremiak** [comment]
Boom, this is exciting! I'll take a look

**Comment by jeremiak** [comment]
@rogeruiz This looks pretty good. So far the only problem I see is the unauthenticated home page after the `THEME` environment variable is set. Here's a screenshot:
screen shot 2015-11-16 at 4 47 28 pm

**Comment by jeremiak** [comment]
Big refactor, nice job @rogeruiz. This is going to keep any/all future collaborators on the project way more sane :)

**Pull request merged**
