### PR TITLE
Add nav bar alt text for user icon (508 compliance)

### PR DESCRIPTION
**Pull request by brandtheisey**
Adds alt text to the image for the user icon in the nav bar to make it 508 Compliant.

### CODE REVIEW

**Comment by brandtheisey** [comment]
It does, however it was the Section 508 Program Manager who noticed and suggested this change. But I agree that your suggestion removes the issue.

**Comment by brandtheisey** [comment]
Updated to say the user's name (or username) in the alt field.

This was suggested by a 508 Program Manager user of ours during the Mission Mexico Pilot.

**Comment by dhcole** [comment]
@brandtheisey I got some guidance from our 508 guru, @nickbristow:

>  Images always need alt, but in this case, it should probably be
> ```alt=''```
> because it provides no additional information. or rather, the information is in text on the screen.
> 
> alt='Davide cole headshot' would work as well, but again, probably unnecessary

How do you feel about going with the empty alt tag so screen readers don't read "Photo of Dave Cole. Dave Cole."

**Comment by brandtheisey** [comment]
Updated

**Comment by dhcole** [comment]
:+1:

**Pull request merged**
