### PR TITLE
Faster dev builds with npm run watch

### PR DESCRIPTION
**Pull request by dhcole**
Some improvements to the development workflow to speed things up. Now, during development, simply run `npm run watch` to start the application and have it restart on changes.

Removes the grunt-based watch task in favor of `npm run watch`, which uses nodemon. Modifies the default grunt task run on `sails lift` to only build the dev assets, which is faster because it avoids uglifying the files.

:ship: :dash:

### CODE REVIEW

**Comment by sefk** [comment]
When I saw the branch named "dev" I was hoping that someone finally decided to rename devel to dev, which I would be **totally** in favor of. Alas, no.

**Comment by sefk** [comment]
Was there a file not checked in? When I tried to run in my dev environment I got an error:

```
sef@speck (dev) midas> npm run watch

> midas@0.3.4 watch /Users/sef/src/18F/midas
> source .env && nodemon --watch assets --watch api --watch config --watch views -i assets/build

sh: .env: No such file or directory

npm ERR! midas@0.3.4 watch: `source .env && nodemon --watch assets --watch api --watch config --watch views -i assets/build`
npm ERR! Exit status 1
```

**Comment by dhcole** [comment]
@sefk thanks for catching that. The watch script should not fail if the `.env` file is missing. I just fixed that and also added documentation for the `.env` file: https://github.com/18F/midas/pull/809/files#diff-6a3371457528722a734f3c51d9238c13

**Comment by sefk** [comment]
Neato! That works now for me, thanks @dhcole 

Those aren't real keys in your .env file docs I trust. :)

**Comment by sefk** [comment]
Suggestion: instead of the command "npm run watch" how about "npm run dev". watch feels more like the "how" instead of the "why." As as user (in this case, a developer) what I want to do is to run the development stack the recommended way, and I believe this will be our recommended way from now on. 

I could also be convinced that this should just replace "npm run start", if that is only used in a dev context. My guess is when you run in production, you start via "node app.js" directly.

**Comment by ultrasaurus** [comment]
FWIW: "watch" is used by other command line tools I've used to mean the same thing, so it felt familiar

**Comment by dhcole** [comment]
@sefk fake I'm afraid. Use them as you wish :)

**Comment by dhcole** [comment]
Also, I've found "watch" to be a fairly standard term for this kind of thing too, so I'd prefer to stick with convention.

**Comment by sefk** [comment]
ok that makes sense!

**Pull request merged**
