### PR TITLE
CSS fix for truncated select2 inputs

### PR DESCRIPTION
**Pull request by dhcole**
Quick fix for a minor but annoying bug:

screen shot 2015-05-01 at 10 57 51 am
screen shot 2015-05-01 at 10 57 19 am

### CODE REVIEW

**Comment by brandtheisey** [comment]
Oh this bugged the heck out of me :+1:

**Comment by ultrasaurus** [comment]
yeah, I couldn't figure out why this was happening to me and not for other people when I noticed this a while back.  

Note:  open opps has its own [application.css](https://github.com/18F/midas-open-opportunities/blob/master/assets/styles/application.css) which appears to have the same bug

**Comment by ultrasaurus** [comment]
@dhcole would you mind filing an issue, which we can keep open until its fixed in both places.

Regretting that I didn't create a separate css file for open opps with overrides... I had intended to refactor to use sass a while back.

**Comment by dhcole** [comment]
Good catch. PR here: https://github.com/18F/midas-open-opportunities/pull/88

**Comment by ultrasaurus** [comment]
Thanks!

**Pull request merged**
