### PR TITLE
Small setup improvements -- nvm to handle nodejs 0.10 dependency

### PR DESCRIPTION
**Pull request by sefk**
amend INSTALL: use nvm for installing node

Now that nodejs has moved on to 0.12 the default instructions (brew install nodejs) are no longer what you want. Midas depends on 0.10, for the time being at least. Instead of fragile instructions on versioning, recommend managing versions with nvm instead.

While in here, ignore vi temp files (*.swp).

### CODE REVIEW

**Comment by ultrasaurus** [comment]
:+1: looks good to me.

**Comment by brandtheisey** [comment]
I like this, but we'll need to look for a windows option for this since we currently support both.

nvmw appears to have a git dependency and we are trying to go away from that.
nvm-windows looks self-contained enough from a surface reading.

@sefk do you happen to know about either of them?

But  :+1: , we don't need to hold up the PR while we figure out the other platform's issues.

**Comment by sefk** [comment]
Thanks for the quick review and pull.

Sorry that I don't know anything about windows here -- indeed I'm new to node myself. So I don't have any wisdom to add on that front. Maybe someone tonight/tomorrow will know. We can watch for those dells/lenovos. :)

**Comment by brandtheisey** [comment]
Was worth a shot just in case, I added a note to the Windows section. Thanks for the PR.

**Pull request merged**
