### PR TITLE
Non-nested comment

### PR DESCRIPTION
**Pull request by monkbroc**
We propose to simplify comments by removing the hierarchy and making it easier for people to write new comments.

current comments

simpler comments

### CODE REVIEW

**Comment by brandtheisey** [comment]
What about prepending every reply  with an @originalauthorsname and making that a href to the comment being replied to? That way to discussion would still be followable if multiple things were going on.

**Comment by brandtheisey** [comment]
:+1: We like this a lot and are going to try out some variations of my comment above before this gets merged in.

**Comment by dhcole** [comment]
This sparked a great discussion. @brandtheisey merged this into #693, which also includes the ability to block quote previous comments. This should balance the flat layout with the need to refer back to previous messages.

**Comment by alan707** [comment]
:+1:

**Pull request closed without merging**
