### PR TITLE
Wall of Fame implementation

### LINKED ISSUE #871: Create a Wall of Fame
The current Open Opportunities [wall of fame](http://gsablogs.gsa.gov/dsic/category/wall-of-fame/) should be implemented in Midas.

Also, this should trigger a notification email to the user: https://github.com/18F/midas/issues/819

### PR DESCRIPTION
**Pull request by jeremiak**
This PR will close #871 and #979 when merged. It implements the concept of the "Wall of Fame" by altering the logged in home page to feeds of the most recent activity on the platform.

Behavior changes:

0. When a user is logged **out** they will not be able to see this view. Instead, they will see our traditional homepage.
0. When a user is logged **in** they will not be able to see the traditional homepage, and instead see this dashboard.

Some development tasks we still need to do to fully enable this interface:
- [ ] Return user objects with agency and/or location if it exists (returning all tags would be fine)
- [x] Implement badging queries or notifications (#979)

### CODE REVIEW

**Comment by dhcole** [comment]
@jeremiak added the controller for the endpoints needed for this. Check the `ActivityController` for the available routes, such as `/api/activity/badges`.

There are a few todos in the comments to finish up, but the format of the API  responses should be stable.

**Comment by jeremiak** [comment]
@dhcole this is exactly what I needed, thanks!

**Comment by dhcole** [comment]
@jeremiak updated the `network` and `count` endpoints to support the standard `where={...}` param, like `http://localhost:1337/api/activity/network` and `http://localhost:1337/api/activity/network?where={%22completedAt%22:%20{%20%22%3E%22:%20%222015-06-01%22}}`

**Comment by jeremiak** [comment]
@dhcole thanks for that enhancement. I can update the activity collection to pass that through so that the closed opportunity count can be from the last 12 months.

@GailSwanson this should now be in a place where its ready for a design critique

**Comment by jeremiak** [comment]
Just finished up the design feedback implementation with @GailSwanson, so I think this is ready for code review/testing @dhcole

**Comment by dhcole** [comment]
@jeremiak: Great work!

I pushed a few small changes to make sure we're escaping content using a different endpoint for the images so we get the default image for users without photos.

screen shot 2015-09-16 at 12 38 07 pm

If you're good with this, then we're ready to :ship:

**Comment by jeremiak** [comment]
@dhcole thanks for those, especially the default profile picture! I'll go ahead and merge

**Pull request merged**
