### PR TITLE
Allow admins to see other users' email addresses

### PR DESCRIPTION
**Pull request by dhcole**
Fixes a bug that came up in v0.6.1

### CODE REVIEW

**Comment by dhcole** [comment]
Also updated to force `username`s (email addresses to lowercase. @jeremiak ready for your review

**Comment by jeremiak** [comment]
Hey @dhcole, code makes sense to me. Where was this bug manifesting? I'm looking at 390e376a6ab37d36de1e67491f10daf100618ff3 and I can still see users' email addresses on their profile an in the admin views.

**Comment by dhcole** [comment]
As an admin, when I look at another user's profile, I do not see their email address. This is what I see for your profile:

screen shot 2015-07-29 at 10 35 56 am

**Comment by jeremiak** [comment]
Understood, LGTM

**Pull request merged**
